#ifndef _GRUTILS_H_
#define _GRUTILS_H_

#define GR_SPACEDIM 3
#define DEFAULT_TENSOR_DIM 3

#define FOR1(IDX) for (int IDX = 0; IDX < DEFAULT_TENSOR_DIM; ++IDX)
#define FOR2(IDX1, IDX2) FOR1(IDX1) FOR1(IDX2)
#define FOR3(IDX1, IDX2, IDX3) FOR2(IDX1, IDX2) FOR1(IDX3)
#define FOR4(IDX1, IDX2, IDX3, IDX4) FOR2(IDX1, IDX2) FOR2(IDX3, IDX4)

#endif /* _GRUTILS_H_*/
